name: build allure python

on: [push, pull_request]

jobs:
  
      
  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get -y install python3.7 python3.7-pip python3.7-venv curl git && \
              python3.7 -m pip install virtualenv && python3.7 -m venv py37-venv && \
              source py37-venv/bin/activate && \
              python3.7 --version && \
              pip install tox && \
              tox -e static-check -c allure-python-commons-test/tox.ini && \
              tox -e static-check -c allure-python-commons/tox.ini && \
              tox -e static-check -c allure-nose2/tox.ini && \
              tox -e static-check -c allure-behave/tox.ini  && \
              tox -e static-check -c allure-pytest/tox.ini && \
              tox -e static-check -c allure-pytest-bdd/tox.ini && \
              tox -e static-check -c allure-robotframework/tox.ini && \
              tox --sdistonly -c ./allure-python-commons && tox --sdistonly -c ./allure-python-commons-test && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-python-commons-test/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-python-commons/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-nose2/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-behave/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-pytest/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-pytest-bdd/tox.ini && \
              tox -e py`echo 3.7 | sed 's/\.//g'` -c allure-robotframework/tox.ini && \
              deactivate'
